### ISSUE TITLE
list in yml file is not correctly quoted

### ISSUE THREAD

**Issue by bachng2017** [bachng2017/dbtdoc#2]
list item is not correct

below is a result from dbtdoc 
```
---
version: 2
models:
  - name: "model02"
    description: "{{ doc('model02') }}"
  - name: "model01"
    description: "{{ doc('model01') }}"
    columns:
      - name: "id"
        type: "integer"
        description: "the only column"
        tests:
          - unique  <-- this is not correct
```
